// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
non_camel_case_types,
unused,
non_snake_case,
clippy::needless_return,
clippy::redundant_closure_call,
clippy::redundant_closure,
clippy::useless_conversion,
clippy::unit_arg,
clippy::unused_unit,
clippy::double_parens,
clippy::let_and_return,
clippy::too_many_arguments,
clippy::match_single_binding,
clippy::clone_on_copy,
clippy::let_unit_value,
clippy::deref_addrof,
clippy::explicit_auto_deref,
clippy::borrow_deref_ref,
clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = SseCodec,
                    default_rust_opaque = RustOpaqueMoi,
                    default_rust_auto_opaque = RustAutoOpaqueMoi,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 2129575494;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__gh_api__flutter_api__create_session_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "create_session", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::gh_common::model::SessionConfig>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::create_session(api_config).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__create_session_v2_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "create_session_v2", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::gh_common::model::SessionConfigV2>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::create_session_v2(api_config).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__dispose_session_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "dispose_session", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::dispose_session(api_session_id).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__get_device_info_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_device_info", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_adb_path = <String>::sse_decode(&mut deserializer);
let api_device_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::get_device_info(api_adb_path, api_device_id).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__get_session_stats_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_session_stats", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::get_session_stats(api_session_id).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__keep_session_event_type_for_flutter_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "keep_session_event_type_for_flutter", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_event = <crate::gh_common::model::SessionEvent>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::gh_api::flutter_api::keep_session_event_type_for_flutter(api_event))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__gh_api__flutter_api__list_devices_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "list_devices", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_adb_path = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::list_devices(api_adb_path).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__request_idr_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "request_idr", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::request_idr(api_session_id).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__send_key_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "send_key", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
let api_event = <crate::gh_common::model::KeyEvent>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::send_key(api_session_id, api_event).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__send_scroll_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "send_scroll", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
let api_event = <crate::gh_common::model::ScrollEvent>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::send_scroll(api_session_id, api_event).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__send_system_key_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "send_system_key", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
let api_key = <crate::gh_common::model::SystemKey>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::send_system_key(api_session_id, api_key).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__send_text_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "send_text", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
let api_text = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::send_text(api_session_id, api_text).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__send_touch_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "send_touch", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
let api_event = <crate::gh_common::model::TouchEvent>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::send_touch(api_session_id, api_event).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__set_clipboard_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "set_clipboard", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
let api_text = <String>::sse_decode(&mut deserializer);
let api_paste = <bool>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::set_clipboard(api_session_id, api_text, api_paste).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__set_orientation_mode_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "set_orientation_mode", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
let api_mode = <crate::gh_common::model::OrientationMode>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::set_orientation_mode(api_session_id, api_mode).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__setup_logger_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "setup_logger", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_max_level = <crate::gh_common::model::LogLevel>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::setup_logger(api_max_level).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__start_session_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "start_session", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::start_session(api_session_id).await?;   Ok(output_ok)
                    })().await)
                } })
            }fn wire__crate__gh_api__flutter_api__stop_session_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec,_,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "stop_session", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context| async move {
                    transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>((move || async move {
                         let output_ok = crate::gh_api::flutter_api::stop_session(api_session_id).await?;   Ok(output_ok)
                    })().await)
                } })
            }

// Section: dart2rust


                impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);}
                }
                
                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for crate::gh_common::model::AndroidKeyEventAction {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::AndroidKeyEventAction::Down,
1 => crate::gh_common::model::AndroidKeyEventAction::Up,
            _ => unreachable!("Invalid variant for AndroidKeyEventAction: {}", inner),
        };}
                }
                
                impl SseDecode for crate::gh_common::model::AndroidMotionEventAction {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::AndroidMotionEventAction::Down,
1 => crate::gh_common::model::AndroidMotionEventAction::Up,
2 => crate::gh_common::model::AndroidMotionEventAction::Move,
3 => crate::gh_common::model::AndroidMotionEventAction::Cancel,
4 => crate::gh_common::model::AndroidMotionEventAction::PointerDown,
5 => crate::gh_common::model::AndroidMotionEventAction::PointerUp,
6 => crate::gh_common::model::AndroidMotionEventAction::HoverMove,
7 => crate::gh_common::model::AndroidMotionEventAction::HoverEnter,
8 => crate::gh_common::model::AndroidMotionEventAction::HoverExit,
            _ => unreachable!("Invalid variant for AndroidMotionEventAction: {}", inner),
        };}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for crate::gh_common::model::DecoderMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::DecoderMode::PreferHardware,
1 => crate::gh_common::model::DecoderMode::ForceHardware,
2 => crate::gh_common::model::DecoderMode::ForceSoftware,
            _ => unreachable!("Invalid variant for DecoderMode: {}", inner),
        };}
                }
                
                impl SseDecode for crate::gh_common::model::DeviceInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_deviceId = <String>::sse_decode(deserializer);
let mut var_model = <String>::sse_decode(deserializer);
let mut var_androidVersion = <String>::sse_decode(deserializer);
let mut var_width = <u32>::sse_decode(deserializer);
let mut var_height = <u32>::sse_decode(deserializer);
let mut var_ip = <Option<String>>::sse_decode(deserializer);
return crate::gh_common::model::DeviceInfo{device_id: var_deviceId, model: var_model, android_version: var_androidVersion, width: var_width, height: var_height, ip: var_ip};}
                }
                
                impl SseDecode for crate::gh_common::model::ErrorCode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::ErrorCode::InvalidSession,
1 => crate::gh_common::model::ErrorCode::AlreadyRunning,
2 => crate::gh_common::model::ErrorCode::NotRunning,
3 => crate::gh_common::model::ErrorCode::DeviceDisconnected,
4 => crate::gh_common::model::ErrorCode::DecodeFailed,
5 => crate::gh_common::model::ErrorCode::TextureFailed,
6 => crate::gh_common::model::ErrorCode::ControlFailed,
7 => crate::gh_common::model::ErrorCode::Internal,
            _ => unreachable!("Invalid variant for ErrorCode: {}", inner),
        };}
                }
                
                impl SseDecode for f32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_f32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_f64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for crate::gh_common::model::KeyEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_action = <crate::gh_common::model::AndroidKeyEventAction>::sse_decode(deserializer);
let mut var_keycode = <u32>::sse_decode(deserializer);
let mut var_repeat = <u32>::sse_decode(deserializer);
let mut var_metastate = <u32>::sse_decode(deserializer);
return crate::gh_common::model::KeyEvent{action: var_action, keycode: var_keycode, repeat: var_repeat, metastate: var_metastate};}
                }
                
                impl SseDecode for Vec<crate::gh_common::model::DeviceInfo> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::gh_common::model::DeviceInfo>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for crate::gh_common::model::LogLevel {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::LogLevel::Trace,
1 => crate::gh_common::model::LogLevel::Debug,
2 => crate::gh_common::model::LogLevel::Info,
3 => crate::gh_common::model::LogLevel::Warn,
4 => crate::gh_common::model::LogLevel::Error,
            _ => unreachable!("Invalid variant for LogLevel: {}", inner),
        };}
                }
                
                impl SseDecode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<String>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for crate::gh_common::model::OrientationChangeSource {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::OrientationChangeSource::ManualApi,
1 => crate::gh_common::model::OrientationChangeSource::AutoSensor,
            _ => unreachable!("Invalid variant for OrientationChangeSource: {}", inner),
        };}
                }
                
                impl SseDecode for crate::gh_common::model::OrientationMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::OrientationMode::Auto,
1 => crate::gh_common::model::OrientationMode::Portrait,
2 => crate::gh_common::model::OrientationMode::Landscape,
            _ => unreachable!("Invalid variant for OrientationMode: {}", inner),
        };}
                }
                
                impl SseDecode for crate::gh_common::model::RenderPipelineMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::RenderPipelineMode::Original,
1 => crate::gh_common::model::RenderPipelineMode::CpuPixelBufferV2,
            _ => unreachable!("Invalid variant for RenderPipelineMode: {}", inner),
        };}
                }
                
                impl SseDecode for crate::gh_common::model::ScrollEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_x = <f32>::sse_decode(deserializer);
let mut var_y = <f32>::sse_decode(deserializer);
let mut var_width = <u32>::sse_decode(deserializer);
let mut var_height = <u32>::sse_decode(deserializer);
let mut var_hscroll = <i32>::sse_decode(deserializer);
let mut var_vscroll = <i32>::sse_decode(deserializer);
return crate::gh_common::model::ScrollEvent{x: var_x, y: var_y, width: var_width, height: var_height, hscroll: var_hscroll, vscroll: var_vscroll};}
                }
                
                impl SseDecode for crate::gh_common::model::SessionConfig {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_adbPath = <String>::sse_decode(deserializer);
let mut var_serverPath = <String>::sse_decode(deserializer);
let mut var_deviceId = <String>::sse_decode(deserializer);
let mut var_maxSize = <u32>::sse_decode(deserializer);
let mut var_bitRate = <u32>::sse_decode(deserializer);
let mut var_maxFps = <u32>::sse_decode(deserializer);
let mut var_videoPort = <u16>::sse_decode(deserializer);
let mut var_controlPort = <u16>::sse_decode(deserializer);
let mut var_videoEncoder = <Option<String>>::sse_decode(deserializer);
let mut var_turnScreenOff = <bool>::sse_decode(deserializer);
let mut var_stayAwake = <bool>::sse_decode(deserializer);
let mut var_scrcpyVerbosity = <String>::sse_decode(deserializer);
let mut var_intraRefreshPeriod = <u32>::sse_decode(deserializer);
return crate::gh_common::model::SessionConfig{adb_path: var_adbPath, server_path: var_serverPath, device_id: var_deviceId, max_size: var_maxSize, bit_rate: var_bitRate, max_fps: var_maxFps, video_port: var_videoPort, control_port: var_controlPort, video_encoder: var_videoEncoder, turn_screen_off: var_turnScreenOff, stay_awake: var_stayAwake, scrcpy_verbosity: var_scrcpyVerbosity, intra_refresh_period: var_intraRefreshPeriod};}
                }
                
                impl SseDecode for crate::gh_common::model::SessionConfigV2 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_base = <crate::gh_common::model::SessionConfig>::sse_decode(deserializer);
let mut var_renderPipelineMode = <crate::gh_common::model::RenderPipelineMode>::sse_decode(deserializer);
let mut var_decoderMode = <crate::gh_common::model::DecoderMode>::sse_decode(deserializer);
return crate::gh_common::model::SessionConfigV2{base: var_base, render_pipeline_mode: var_renderPipelineMode, decoder_mode: var_decoderMode};}
                }
                
                impl SseDecode for crate::gh_common::model::SessionEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut tag_ = <i32>::sse_decode(deserializer);
            match tag_ {0 => { return crate::gh_common::model::SessionEvent::Starting; }
1 => { return crate::gh_common::model::SessionEvent::Running; }
2 => { return crate::gh_common::model::SessionEvent::Reconnecting; }
3 => { return crate::gh_common::model::SessionEvent::Stopped; }
4 => { let mut var_code = <crate::gh_common::model::ErrorCode>::sse_decode(deserializer);
let mut var_message = <String>::sse_decode(deserializer);
return crate::gh_common::model::SessionEvent::Error{code: var_code, message: var_message}; }
5 => { let mut var_mode = <crate::gh_common::model::OrientationMode>::sse_decode(deserializer);
let mut var_source = <crate::gh_common::model::OrientationChangeSource>::sse_decode(deserializer);
return crate::gh_common::model::SessionEvent::OrientationChanged{mode: var_mode, source: var_source}; }
6 => { let mut var_width = <u32>::sse_decode(deserializer);
let mut var_height = <u32>::sse_decode(deserializer);
let mut var_newHandle = <i64>::sse_decode(deserializer);
let mut var_generation = <u64>::sse_decode(deserializer);
return crate::gh_common::model::SessionEvent::ResolutionChanged{width: var_width, height: var_height, new_handle: var_newHandle, generation: var_generation}; }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseDecode for crate::gh_common::model::SessionStats {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_fps = <f64>::sse_decode(deserializer);
let mut var_decodeLatencyMs = <u32>::sse_decode(deserializer);
let mut var_uploadLatencyMs = <u32>::sse_decode(deserializer);
let mut var_totalFrames = <u64>::sse_decode(deserializer);
let mut var_droppedFrames = <u64>::sse_decode(deserializer);
return crate::gh_common::model::SessionStats{fps: var_fps, decode_latency_ms: var_decodeLatencyMs, upload_latency_ms: var_uploadLatencyMs, total_frames: var_totalFrames, dropped_frames: var_droppedFrames};}
                }
                
                impl SseDecode for crate::gh_common::model::SystemKey {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::gh_common::model::SystemKey::Home,
1 => crate::gh_common::model::SystemKey::Back,
2 => crate::gh_common::model::SystemKey::Recent,
3 => crate::gh_common::model::SystemKey::PowerMenu,
4 => crate::gh_common::model::SystemKey::VolumeUp,
5 => crate::gh_common::model::SystemKey::VolumeDown,
6 => crate::gh_common::model::SystemKey::RotateScreen,
            _ => unreachable!("Invalid variant for SystemKey: {}", inner),
        };}
                }
                
                impl SseDecode for crate::gh_common::model::TouchEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_action = <crate::gh_common::model::AndroidMotionEventAction>::sse_decode(deserializer);
let mut var_pointerId = <i64>::sse_decode(deserializer);
let mut var_x = <f32>::sse_decode(deserializer);
let mut var_y = <f32>::sse_decode(deserializer);
let mut var_pressure = <f32>::sse_decode(deserializer);
let mut var_width = <u32>::sse_decode(deserializer);
let mut var_height = <u32>::sse_decode(deserializer);
let mut var_buttons = <u32>::sse_decode(deserializer);
return crate::gh_common::model::TouchEvent{action: var_action, pointer_id: var_pointerId, x: var_x, y: var_y, pressure: var_pressure, width: var_width, height: var_height, buttons: var_buttons};}
                }
                
                impl SseDecode for u16 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u16::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        1 => wire__crate__gh_api__flutter_api__create_session_impl(port, ptr, rust_vec_len, data_len),
2 => wire__crate__gh_api__flutter_api__create_session_v2_impl(port, ptr, rust_vec_len, data_len),
3 => wire__crate__gh_api__flutter_api__dispose_session_impl(port, ptr, rust_vec_len, data_len),
4 => wire__crate__gh_api__flutter_api__get_device_info_impl(port, ptr, rust_vec_len, data_len),
5 => wire__crate__gh_api__flutter_api__get_session_stats_impl(port, ptr, rust_vec_len, data_len),
6 => wire__crate__gh_api__flutter_api__keep_session_event_type_for_flutter_impl(port, ptr, rust_vec_len, data_len),
7 => wire__crate__gh_api__flutter_api__list_devices_impl(port, ptr, rust_vec_len, data_len),
8 => wire__crate__gh_api__flutter_api__request_idr_impl(port, ptr, rust_vec_len, data_len),
9 => wire__crate__gh_api__flutter_api__send_key_impl(port, ptr, rust_vec_len, data_len),
10 => wire__crate__gh_api__flutter_api__send_scroll_impl(port, ptr, rust_vec_len, data_len),
11 => wire__crate__gh_api__flutter_api__send_system_key_impl(port, ptr, rust_vec_len, data_len),
12 => wire__crate__gh_api__flutter_api__send_text_impl(port, ptr, rust_vec_len, data_len),
13 => wire__crate__gh_api__flutter_api__send_touch_impl(port, ptr, rust_vec_len, data_len),
14 => wire__crate__gh_api__flutter_api__set_clipboard_impl(port, ptr, rust_vec_len, data_len),
15 => wire__crate__gh_api__flutter_api__set_orientation_mode_impl(port, ptr, rust_vec_len, data_len),
16 => wire__crate__gh_api__flutter_api__setup_logger_impl(port, ptr, rust_vec_len, data_len),
17 => wire__crate__gh_api__flutter_api__start_session_impl(port, ptr, rust_vec_len, data_len),
18 => wire__crate__gh_api__flutter_api__stop_session_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::AndroidKeyEventAction {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Down => 0.into_dart(),
Self::Up => 1.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::AndroidKeyEventAction {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::AndroidKeyEventAction> for crate::gh_common::model::AndroidKeyEventAction {
            fn into_into_dart(self) -> crate::gh_common::model::AndroidKeyEventAction {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::AndroidMotionEventAction {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Down => 0.into_dart(),
Self::Up => 1.into_dart(),
Self::Move => 2.into_dart(),
Self::Cancel => 3.into_dart(),
Self::PointerDown => 4.into_dart(),
Self::PointerUp => 5.into_dart(),
Self::HoverMove => 6.into_dart(),
Self::HoverEnter => 7.into_dart(),
Self::HoverExit => 8.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::AndroidMotionEventAction {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::AndroidMotionEventAction> for crate::gh_common::model::AndroidMotionEventAction {
            fn into_into_dart(self) -> crate::gh_common::model::AndroidMotionEventAction {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::DecoderMode {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::PreferHardware => 0.into_dart(),
Self::ForceHardware => 1.into_dart(),
Self::ForceSoftware => 2.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::DecoderMode {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::DecoderMode> for crate::gh_common::model::DecoderMode {
            fn into_into_dart(self) -> crate::gh_common::model::DecoderMode {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::DeviceInfo {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.device_id.into_into_dart().into_dart(),
self.model.into_into_dart().into_dart(),
self.android_version.into_into_dart().into_dart(),
self.width.into_into_dart().into_dart(),
self.height.into_into_dart().into_dart(),
self.ip.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::DeviceInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::DeviceInfo> for crate::gh_common::model::DeviceInfo {
            fn into_into_dart(self) -> crate::gh_common::model::DeviceInfo {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::ErrorCode {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::InvalidSession => 0.into_dart(),
Self::AlreadyRunning => 1.into_dart(),
Self::NotRunning => 2.into_dart(),
Self::DeviceDisconnected => 3.into_dart(),
Self::DecodeFailed => 4.into_dart(),
Self::TextureFailed => 5.into_dart(),
Self::ControlFailed => 6.into_dart(),
Self::Internal => 7.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::ErrorCode {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::ErrorCode> for crate::gh_common::model::ErrorCode {
            fn into_into_dart(self) -> crate::gh_common::model::ErrorCode {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::KeyEvent {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.action.into_into_dart().into_dart(),
self.keycode.into_into_dart().into_dart(),
self.repeat.into_into_dart().into_dart(),
self.metastate.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::KeyEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::KeyEvent> for crate::gh_common::model::KeyEvent {
            fn into_into_dart(self) -> crate::gh_common::model::KeyEvent {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::LogLevel {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Trace => 0.into_dart(),
Self::Debug => 1.into_dart(),
Self::Info => 2.into_dart(),
Self::Warn => 3.into_dart(),
Self::Error => 4.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::LogLevel {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::LogLevel> for crate::gh_common::model::LogLevel {
            fn into_into_dart(self) -> crate::gh_common::model::LogLevel {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::OrientationChangeSource {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::ManualApi => 0.into_dart(),
Self::AutoSensor => 1.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::OrientationChangeSource {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::OrientationChangeSource> for crate::gh_common::model::OrientationChangeSource {
            fn into_into_dart(self) -> crate::gh_common::model::OrientationChangeSource {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::OrientationMode {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Auto => 0.into_dart(),
Self::Portrait => 1.into_dart(),
Self::Landscape => 2.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::OrientationMode {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::OrientationMode> for crate::gh_common::model::OrientationMode {
            fn into_into_dart(self) -> crate::gh_common::model::OrientationMode {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::RenderPipelineMode {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Original => 0.into_dart(),
Self::CpuPixelBufferV2 => 1.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::RenderPipelineMode {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::RenderPipelineMode> for crate::gh_common::model::RenderPipelineMode {
            fn into_into_dart(self) -> crate::gh_common::model::RenderPipelineMode {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::ScrollEvent {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.x.into_into_dart().into_dart(),
self.y.into_into_dart().into_dart(),
self.width.into_into_dart().into_dart(),
self.height.into_into_dart().into_dart(),
self.hscroll.into_into_dart().into_dart(),
self.vscroll.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::ScrollEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::ScrollEvent> for crate::gh_common::model::ScrollEvent {
            fn into_into_dart(self) -> crate::gh_common::model::ScrollEvent {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::SessionConfig {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.adb_path.into_into_dart().into_dart(),
self.server_path.into_into_dart().into_dart(),
self.device_id.into_into_dart().into_dart(),
self.max_size.into_into_dart().into_dart(),
self.bit_rate.into_into_dart().into_dart(),
self.max_fps.into_into_dart().into_dart(),
self.video_port.into_into_dart().into_dart(),
self.control_port.into_into_dart().into_dart(),
self.video_encoder.into_into_dart().into_dart(),
self.turn_screen_off.into_into_dart().into_dart(),
self.stay_awake.into_into_dart().into_dart(),
self.scrcpy_verbosity.into_into_dart().into_dart(),
self.intra_refresh_period.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::SessionConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::SessionConfig> for crate::gh_common::model::SessionConfig {
            fn into_into_dart(self) -> crate::gh_common::model::SessionConfig {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::SessionConfigV2 {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.base.into_into_dart().into_dart(),
self.render_pipeline_mode.into_into_dart().into_dart(),
self.decoder_mode.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::SessionConfigV2 {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::SessionConfigV2> for crate::gh_common::model::SessionConfigV2 {
            fn into_into_dart(self) -> crate::gh_common::model::SessionConfigV2 {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::SessionEvent {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {crate::gh_common::model::SessionEvent::Starting => { [0.into_dart()].into_dart() }
crate::gh_common::model::SessionEvent::Running => { [1.into_dart()].into_dart() }
crate::gh_common::model::SessionEvent::Reconnecting => { [2.into_dart()].into_dart() }
crate::gh_common::model::SessionEvent::Stopped => { [3.into_dart()].into_dart() }
crate::gh_common::model::SessionEvent::Error{code,message} => { [4.into_dart(),
code.into_into_dart().into_dart(),
message.into_into_dart().into_dart()].into_dart() }
crate::gh_common::model::SessionEvent::OrientationChanged{mode,source} => { [5.into_dart(),
mode.into_into_dart().into_dart(),
source.into_into_dart().into_dart()].into_dart() }
crate::gh_common::model::SessionEvent::ResolutionChanged{width,height,new_handle,generation} => { [6.into_dart(),
width.into_into_dart().into_dart(),
height.into_into_dart().into_dart(),
new_handle.into_into_dart().into_dart(),
generation.into_into_dart().into_dart()].into_dart() }
 _ => { unimplemented!(""); }}
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::SessionEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::SessionEvent> for crate::gh_common::model::SessionEvent {
            fn into_into_dart(self) -> crate::gh_common::model::SessionEvent {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::SessionStats {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.fps.into_into_dart().into_dart(),
self.decode_latency_ms.into_into_dart().into_dart(),
self.upload_latency_ms.into_into_dart().into_dart(),
self.total_frames.into_into_dart().into_dart(),
self.dropped_frames.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::SessionStats {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::SessionStats> for crate::gh_common::model::SessionStats {
            fn into_into_dart(self) -> crate::gh_common::model::SessionStats {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::SystemKey {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Home => 0.into_dart(),
Self::Back => 1.into_dart(),
Self::Recent => 2.into_dart(),
Self::PowerMenu => 3.into_dart(),
Self::VolumeUp => 4.into_dart(),
Self::VolumeDown => 5.into_dart(),
Self::RotateScreen => 6.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::SystemKey {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::SystemKey> for crate::gh_common::model::SystemKey {
            fn into_into_dart(self) -> crate::gh_common::model::SystemKey {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::gh_common::model::TouchEvent {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.action.into_into_dart().into_dart(),
self.pointer_id.into_into_dart().into_dart(),
self.x.into_into_dart().into_dart(),
self.y.into_into_dart().into_dart(),
self.pressure.into_into_dart().into_dart(),
self.width.into_into_dart().into_dart(),
self.height.into_into_dart().into_dart(),
self.buttons.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::gh_common::model::TouchEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::gh_common::model::TouchEvent> for crate::gh_common::model::TouchEvent {
            fn into_into_dart(self) -> crate::gh_common::model::TouchEvent {
                self
            }
        }

                impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(format!("{:?}", self), serializer);}
                }
                
                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::AndroidKeyEventAction {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::AndroidKeyEventAction::Down => { 0 }
crate::gh_common::model::AndroidKeyEventAction::Up => { 1 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::AndroidMotionEventAction {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::AndroidMotionEventAction::Down => { 0 }
crate::gh_common::model::AndroidMotionEventAction::Up => { 1 }
crate::gh_common::model::AndroidMotionEventAction::Move => { 2 }
crate::gh_common::model::AndroidMotionEventAction::Cancel => { 3 }
crate::gh_common::model::AndroidMotionEventAction::PointerDown => { 4 }
crate::gh_common::model::AndroidMotionEventAction::PointerUp => { 5 }
crate::gh_common::model::AndroidMotionEventAction::HoverMove => { 6 }
crate::gh_common::model::AndroidMotionEventAction::HoverEnter => { 7 }
crate::gh_common::model::AndroidMotionEventAction::HoverExit => { 8 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for crate::gh_common::model::DecoderMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::DecoderMode::PreferHardware => { 0 }
crate::gh_common::model::DecoderMode::ForceHardware => { 1 }
crate::gh_common::model::DecoderMode::ForceSoftware => { 2 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::DeviceInfo {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.device_id, serializer);
<String>::sse_encode(self.model, serializer);
<String>::sse_encode(self.android_version, serializer);
<u32>::sse_encode(self.width, serializer);
<u32>::sse_encode(self.height, serializer);
<Option<String>>::sse_encode(self.ip, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::ErrorCode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::ErrorCode::InvalidSession => { 0 }
crate::gh_common::model::ErrorCode::AlreadyRunning => { 1 }
crate::gh_common::model::ErrorCode::NotRunning => { 2 }
crate::gh_common::model::ErrorCode::DeviceDisconnected => { 3 }
crate::gh_common::model::ErrorCode::DecodeFailed => { 4 }
crate::gh_common::model::ErrorCode::TextureFailed => { 5 }
crate::gh_common::model::ErrorCode::ControlFailed => { 6 }
crate::gh_common::model::ErrorCode::Internal => { 7 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for f32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_f32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_f64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for crate::gh_common::model::KeyEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<crate::gh_common::model::AndroidKeyEventAction>::sse_encode(self.action, serializer);
<u32>::sse_encode(self.keycode, serializer);
<u32>::sse_encode(self.repeat, serializer);
<u32>::sse_encode(self.metastate, serializer);}
                }
                
                impl SseEncode for Vec<crate::gh_common::model::DeviceInfo> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::gh_common::model::DeviceInfo>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for crate::gh_common::model::LogLevel {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::LogLevel::Trace => { 0 }
crate::gh_common::model::LogLevel::Debug => { 1 }
crate::gh_common::model::LogLevel::Info => { 2 }
crate::gh_common::model::LogLevel::Warn => { 3 }
crate::gh_common::model::LogLevel::Error => { 4 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <String>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for crate::gh_common::model::OrientationChangeSource {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::OrientationChangeSource::ManualApi => { 0 }
crate::gh_common::model::OrientationChangeSource::AutoSensor => { 1 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::OrientationMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::OrientationMode::Auto => { 0 }
crate::gh_common::model::OrientationMode::Portrait => { 1 }
crate::gh_common::model::OrientationMode::Landscape => { 2 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::RenderPipelineMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::RenderPipelineMode::Original => { 0 }
crate::gh_common::model::RenderPipelineMode::CpuPixelBufferV2 => { 1 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::ScrollEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<f32>::sse_encode(self.x, serializer);
<f32>::sse_encode(self.y, serializer);
<u32>::sse_encode(self.width, serializer);
<u32>::sse_encode(self.height, serializer);
<i32>::sse_encode(self.hscroll, serializer);
<i32>::sse_encode(self.vscroll, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::SessionConfig {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.adb_path, serializer);
<String>::sse_encode(self.server_path, serializer);
<String>::sse_encode(self.device_id, serializer);
<u32>::sse_encode(self.max_size, serializer);
<u32>::sse_encode(self.bit_rate, serializer);
<u32>::sse_encode(self.max_fps, serializer);
<u16>::sse_encode(self.video_port, serializer);
<u16>::sse_encode(self.control_port, serializer);
<Option<String>>::sse_encode(self.video_encoder, serializer);
<bool>::sse_encode(self.turn_screen_off, serializer);
<bool>::sse_encode(self.stay_awake, serializer);
<String>::sse_encode(self.scrcpy_verbosity, serializer);
<u32>::sse_encode(self.intra_refresh_period, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::SessionConfigV2 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<crate::gh_common::model::SessionConfig>::sse_encode(self.base, serializer);
<crate::gh_common::model::RenderPipelineMode>::sse_encode(self.render_pipeline_mode, serializer);
<crate::gh_common::model::DecoderMode>::sse_encode(self.decoder_mode, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::SessionEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {match self {crate::gh_common::model::SessionEvent::Starting => { <i32>::sse_encode(0, serializer);  }
crate::gh_common::model::SessionEvent::Running => { <i32>::sse_encode(1, serializer);  }
crate::gh_common::model::SessionEvent::Reconnecting => { <i32>::sse_encode(2, serializer);  }
crate::gh_common::model::SessionEvent::Stopped => { <i32>::sse_encode(3, serializer);  }
crate::gh_common::model::SessionEvent::Error{code,message} => { <i32>::sse_encode(4, serializer); <crate::gh_common::model::ErrorCode>::sse_encode(code, serializer);
<String>::sse_encode(message, serializer);
 }
crate::gh_common::model::SessionEvent::OrientationChanged{mode,source} => { <i32>::sse_encode(5, serializer); <crate::gh_common::model::OrientationMode>::sse_encode(mode, serializer);
<crate::gh_common::model::OrientationChangeSource>::sse_encode(source, serializer);
 }
crate::gh_common::model::SessionEvent::ResolutionChanged{width,height,new_handle,generation} => { <i32>::sse_encode(6, serializer); <u32>::sse_encode(width, serializer);
<u32>::sse_encode(height, serializer);
<i64>::sse_encode(new_handle, serializer);
<u64>::sse_encode(generation, serializer);
 }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseEncode for crate::gh_common::model::SessionStats {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<f64>::sse_encode(self.fps, serializer);
<u32>::sse_encode(self.decode_latency_ms, serializer);
<u32>::sse_encode(self.upload_latency_ms, serializer);
<u64>::sse_encode(self.total_frames, serializer);
<u64>::sse_encode(self.dropped_frames, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::SystemKey {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::gh_common::model::SystemKey::Home => { 0 }
crate::gh_common::model::SystemKey::Back => { 1 }
crate::gh_common::model::SystemKey::Recent => { 2 }
crate::gh_common::model::SystemKey::PowerMenu => { 3 }
crate::gh_common::model::SystemKey::VolumeUp => { 4 }
crate::gh_common::model::SystemKey::VolumeDown => { 5 }
crate::gh_common::model::SystemKey::RotateScreen => { 6 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::gh_common::model::TouchEvent {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<crate::gh_common::model::AndroidMotionEventAction>::sse_encode(self.action, serializer);
<i64>::sse_encode(self.pointer_id, serializer);
<f32>::sse_encode(self.x, serializer);
<f32>::sse_encode(self.y, serializer);
<f32>::sse_encode(self.pressure, serializer);
<u32>::sse_encode(self.width, serializer);
<u32>::sse_encode(self.height, serializer);
<u32>::sse_encode(self.buttons, serializer);}
                }
                
                impl SseEncode for u16 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u16::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();


        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        